INSERT INTO CPL.player 
    (name, role, jersey_number, jersey_size, payment_status)
VALUES
    ('Muna', 'All Rounder', 45, 'M', 'Unpaid'),
    ('Guddu', 'All Rounder', 7, 'M', 'Unpaid'),
    ('Rajsekhar', 'Bowler', 7, 'M', 'Unpaid'),
    ('Anil Dakua', 'Bowler', 4, 'L', 'Unpaid'),
    ('Sukanta Hati', 'All Rounder', 45, 'XL', 'Unpaid'),
    ('Suraj', 'All Rounder', 7, 'XXXL', 'Unpaid'),
    ('Soumya', 'Batsman', 18, 'XXL', 'Unpaid'),
    ('Deepu', 'Batsman', 10, 'L', 'Unpaid'),
    ('Jatin', 'Bowler', 7, 'XL', 'Unpaid'),
    ('Anil', 'All Rounder', 23, 'L', 'Unpaid'),
    ('Saroj', 'All Rounder', 18, 'M', 'Unpaid'),
    ('Rudhi', 'All Rounder', 7, 'L', 'Unpaid'),
    ('Jitun', 'All Rounder', 18, 'L', 'Unpaid'),
    ('Ranjit', 'Bowler', 64, 'L', 'Unpaid'),
    ('Yadab', 'Bowler', 22, 'XL', 'Unpaid'),
    ('Santosh', 'All Rounder', 99, 'M', 'Unpaid'),
    ('Gyana', 'Batsman', 7, 'XL', 'Unpaid'),
    ('Kotesh', 'Batsman', 20, 'XXL', 'Unpaid'),
    ('Sana', 'Batsman', 27, 'L', 'Unpaid'),
    ('Sibuna', 'All Rounder', 10, 'L', 'Unpaid'),
    ('SB', 'All Rounder', 24, 'XXXL', 'Unpaid'),
    ('Pupu', 'All Rounder', 3, 'M', 'Unpaid'),
    ('Manas', 'All Rounder', 8, 'M', 'Unpaid'),
    ('Sunil', 'Batsman', 7, 'L', 'Unpaid'),
    ('Lipu', 'Bowler', 1, 'M', 'Unpaid'),
    ('Surya', 'Batsman', 12, 'XL', 'Unpaid'),
    ('Priya', 'Batsman', 72, 'XXL', 'Unpaid'),
    ('Arun', 'Batsman', 7, 'L', 'Unpaid'),
    ('Sudhanshu', 'All Rounder', 80, 'XL', 'Unpaid'),
    ('Bisu', 'All Rounder', 41, 'XXXL', 'Unpaid'),
    ('Rameswar Parhi', 'Bowler', 5, 'L', 'Unpaid'),
    ('Piku', 'All Rounder', 30, 'L', 'Unpaid'),
    ('Lalu', 'All Rounder', 7, 'M', 'Unpaid'),
    ('Rakesh', 'All Rounder', 20, 'L', 'Unpaid'),
    ('Tapan', 'All Rounder', 11, 'L', 'Unpaid'),
    ('Linga', 'Batsman', 69, 'XL', 'Unpaid'),
    ('Mitu', 'All Rounder', 83, 'XXL', 'Unpaid'),
    ('Bubu', 'All Rounder', 99, 'M', 'Unpaid'),
    ('Li2', 'Bowler', 99, 'XL', 'Unpaid'),
    ('Papu', 'All Rounder', 16, 'XL', 'Unpaid'),
    ('Lingaraj', 'Batsman', 15, 'L', 'Unpaid'),
    ('Bikas', 'Bowler', 23, 'S', 'Unpaid'),
    ('Prakash', 'Bowler', 64, 'L', 'Unpaid'),
    ('Pipi', 'Batsman', 11, 'L', 'Unpaid'),
    ('Sangram', 'Bowler', 7, 'M', 'Unpaid'),
    ('Manash', 'Bowler', 8, 'S', 'Unpaid'),
    ('Pinu', 'Bowler', 15, 'M', 'Unpaid'),
    ('Tutu', 'Bowler', 22, 'L', 'Unpaid'),
    ('Babul', 'Bowler', 7, 'S', 'Unpaid'),
    ('Raja', 'All Rounder', 45, 'XL', 'Unpaid'),
    ('Chandan', 'All Rounder', 18, 'S', 'Unpaid'),
    ('Milu', 'All Rounder', 33, 'XL', 'Unpaid'),
    ('Babu', 'Batsman', 99, 'XXL', 'Unpaid'),
    ('Ashis', 'Batsman', 99, 'L', 'Unpaid'),
    ('Deba', 'Bowler', 7, 'XXXL', 'Unpaid'),
    ('Mohit', 'All Rounder', 45, 'M', 'Unpaid'),
    ('Sipu', 'All Rounder', 10, 'S', 'Unpaid'),
    ('Bikash', 'All Rounder', 55, 'XL', 'Unpaid'),
    ('Dev', 'Batsman', 7, 'XL', 'Unpaid'),
    ('Papuni', 'All Rounder', 180, 'XXL', 'Unpaid'),
    ('Abhi', 'Bowler', 42, 'XL', 'Unpaid'),
    ('Rintu', 'All Rounder', 9, 'XL', 'Unpaid'),
    ('Subhrajit', 'All Rounder', 112, 'S', 'Unpaid'),
    ('Subha', 'All Rounder', 5, 'XXL', 'Unpaid'),
    ('Raja', 'All Rounder', 16, 'XL', 'Unpaid'),
    ('Babun', 'All Rounder', 8, 'S', 'Unpaid'),
    ('Kanhu', 'All Rounder', 72, 'M', 'Unpaid'),
    ('Sipun Behera', 'All Rounder', 7, 'L', 'Unpaid'),
    ('Bapi', 'Batsman', 88, 'XL', 'Unpaid'),
    ('Raja', 'Batsman', 5, 'XXL', 'Unpaid'),
    ('Muna', 'Batsman', 22, 'L', 'Unpaid'),
    ('Sahil', 'All Rounder', 2, 'XL', 'Unpaid');
    
    
    -- Add Season
    insert into CPL.season (year) values (2025),(2026);
    
    -- Add Teams
    INSERT INTO CPL.team (name ,short_code, city, team_picture_url, coach)
values
(Aahan,	AH,	Bhubaneswar, https://res.cloudinary.com/dni3icbrx/image/upload/v1764485263/iwacsbfsy0lgbpop75o7.png, Sangram),
(Vision Shilpi,	VS,	Bhubaneswar, https://res.cloudinary.com/dni3icbrx/image/upload/v1764485291/zruvfvjszcx0tovu94ex.png,Pupu),
(Thunder Strikers,	TH	Bhubaneswar,	https://res.cloudinary.com/dni3icbrx/image/upload/v1764485320/webahmneqazmzsgpagfj.png,Papu),
(NSOLN,	NL,	Bhubaneswar,	https://res.cloudinary.com/dni3icbrx/image/upload/v1764485342/x34puco5yhdmgs1gz8tz.png,Jadumani);
    


